### ISSUE TITLE
Unable to use any other Laravel 5 versions other than 5.5

### ISSUE THREAD

**Issue by denizaygun** [salamwaddah/laravel-mandrill-driver#15]
In your `composer.json` you have the following:

`        "illuminate/notifications": "5.5.* || ^6.0 || ^7.0",
        "illuminate/support": "5.5.* || ^6.0 || ^7.0"` 

By requiring 5.5.*, you are preventing other versions of Laravel5 such as 5.7 and 5.8, I would recommend changing this to ^5.0 or 5.*

**Comment by salamwaddah** [comment]
Fixed in https://github.com/salamwaddah/laravel-mandrill-driver/releases/tag/1.1.2
